#' Simulation function for s3CA
#'
#' This function performs simulation to prove the use of s3CA in estimating the target latent factor. The data will be generated by simulating their covariance matrix.
#' @import PMA
#' @import MASS
#' @param nt sample size of target group.
#' @param na sample size of ancillary group.
#' @param p dimension of one data type denote as X.
#' @param q dimension of another data type denote as Y.
#' @param s number of non-zero loadings in each singular vector.
#' @param AR: values of the first off-diaonal element for toeplitz matrices which are set to be the error covariance matrix for Xt and Yt. The error covariances for Xa and Ya are set to be 0.1 times identity matrices.
#' @param lambda_t eigenvalues for U1V1, U2V2, U3V3 and U4V4 in target group.
#' @param lambda_a eigenvalues for U1V1, U2V2 in ancillary group.
#' @param eta the tuning parameter between target and ancillary group, if eta = NULL, will use eta estimation.
#' @param lm_sigma the error standard deviation of regression which is used for validation of methods.
#' @param lm_beta the coefficient of regression which is used for validation of methods.
#' @param repetition the number of replications for simulation.
#' @return A data frame containing the estimation of regression coefficients from 3CA, target cross covariance analysis, and cPCA on one data type.
#' @export
#' @examples
#' #library(CEA)
#' #library(ggplot2)
#' #library(ggsci)
#' #library(ggh4x)
#' #library(tidyverse)
#' #n_candidates <- c(3000)
#' #AR_candidates <- c(0.5, 0.7, 0.9)
#' #p_candidates <- c(300, 350, 400)
#' #s_candidates <- c(5,10)
#' #results <- setNames(data.frame(matrix(ncol = 7, nrow = 0)),
#' #                    c("est_trt_cca", "est_ctst_cca", "est_ctst_pca", "eta_est",
#' #                      "Dimension", "AR","Sparsity"))
#' #for (n in n_candidates) {
#' #  for (AR in AR_candidates){
#' #    for (p in p_candidates) {
#' #      for (s in s_candidates) {
#' #        res <- sim_s3CA(nt = n, na = n, p = p, q = p, s = s,
#' #                         lambda_t = c(6, 4, 2, 0), lambda_c = c(2, 0.2), eta = NULL,
#' #                         AR = AR, lm_sigma = 1, lm_beta = 1.5, repetition = 10)
#' #        rownames(res) <- NULL
#' #        res$Dimension <- p
#' #        res$AR <- AR
#' #        res$Sparsity <- s
#' #        results <- rbind(results, res)
#' #      }
#' #    }
#' #  }
#' #}
#' #knitr::kable(results, format = "markdown")
#' #plot_results <- pivot_longer(results, 1:3, names_to = "Type", values_to = "Estimation")
#' #plot_results$Analysis <- sub(".*?_", "", plot_results$Type)
#' #plot_results$Dimension <- paste("p=", plot_results$Dimension, sep = "")
#' #plot_results$AR <- paste("AR=", plot_results$AR, sep = "")
#' #plot_results$Analysis <- factor(plot_results$Analysis, labels = c("ContrastiveCCA", "ContrastivePCA", "TargetCCA"))
#' #plot_results$Sparsity <- paste("# of non-zero elements =", plot_results$Sparsity)
#' #sp_est_box <- ggplot(data = plot_results[plot_results$Sparsity != "# of non-zero elements = 5",])+
#' #  geom_boxplot(aes(x = factor(Analysis, levels=c("ContrastiveCCA", "ContrastivePCA", "TargetCCA"), labels=c("s3CA", "scPCA", "trtsCCA")), y = abs(Estimation), fill = Analysis), show.legend = FALSE)+
#' #  facet_nested(AR~Sparsity+Dimension)+
#' #  geom_hline(yintercept = 1.5, linetype = "dashed", color="red")+
#' #  scale_y_continuous(breaks = c( 0, 1.5))+
#' #  theme_bw()+
#' #  theme(
#' #    panel.grid = element_blank(),
#' #    strip.background = element_rect(fill = "lightblue", color = "black"),
#' #    strip.text = element_text(color = "black", face = "bold", size = 14),
#' #    text = element_text(size = 14),  # Adjust text size
#' #    axis.title = element_text(size = 16),  # Adjust axis title size
#' #    axis.text = element_text(size = 12)   # Adjust axis text size
#' #  )+
#' #  scale_fill_d3()+
#' #  labs(y = "Estimation of the coefficient in (3.1)",x="Analysis")
#' #print(sp_est_box)

sim_s3CA <- function(nt, na, p, q, s, AR,
                      lambda_t = c(3, 2, 1, 0), lambda_a = c(3, 2), eta = NULL,
                      lm_sigma = 1, lm_beta = 1.5, repetition = 10){

  # error covariances
  Phi_t <- toeplitz(AR^(0:(p-1)))
  Phi_a <- diag(0.1, p)
  Psi_t <- toeplitz(AR^(0:(q-1)))
  Psi_a <- diag(0.1, q)

  # latent factors
  u1 <- matrix(rep(c(1,0), c(s, p-s)), nrow = p, ncol = 1)
  u2 <- matrix(rep(c(0,1,0), c(s,s, p-2*s)), nrow = p, ncol = 1)
  u3 <- matrix(rep(c(0,0,1,0), c(s,s,s,p-3*s)), nrow = p, ncol = 1)
  u4 <- matrix(rep(c(0,0,0,1,0), c(s,s,s,s,p-4*s)), nrow = p, ncol = 1)

  v1 <- matrix(rep(c(1,0), c(s, q-s)), nrow = q, ncol = 1)
  v2 <- matrix(rep(c(0,1,0), c(s,s, q-2*s)), nrow = q, ncol = 1)
  v3 <- matrix(rep(c(0,0,1,0), c(s,s,s,q-3*s)), nrow = q, ncol = 1)
  v4 <- matrix(rep(c(0,0,0,1,0), c(s,s,s,s,q-4*s)), nrow = q, ncol = 1)

  u1 <- u1/norm(u1,"2")
  u2 <- u2/norm(u2,"2")
  u3 <- u3/norm(u3,"2")
  u4 <- u4/norm(u4,"2")

  v1 <- v1/norm(v1,"2")
  v2 <- v2/norm(v2,"2")
  v3 <- v3/norm(v3,"2")
  v4 <- v4/norm(v4,"2")

  # variance-covariance matrices for (x,y) in target group or ancillary group based on paper model

  Sigma_t <- rbind(cbind(lambda_t[1]*u1%*%t(u1)+lambda_t[2]*u2%*%t(u2)+lambda_t[3]*u3%*%t(u3)+lambda_t[4]*u4%*%t(u4)+Phi_t,
                         lambda_t[1]*u1%*%t(v1)+lambda_t[3]*u3%*%t(v3)),
                   cbind(lambda_t[1]*v1%*%t(u1)+lambda_t[3]*v3%*%t(u3),
                         lambda_t[1]*v1%*%t(v1)+lambda_t[2]*v2%*%t(v2)+lambda_t[3]*v3%*%t(v3)+lambda_t[4]*v4%*%t(v4)+Psi_t))
  Sigma_a <- rbind(cbind(lambda_a[1]*u1%*%t(u1)+lambda_a[2]*u2%*%t(u2)+Phi_a,
                         lambda_a[1]*u1%*%t(v1)),
                   cbind(lambda_a[1]*v1%*%t(u1),
                         lambda_a[1]*v1%*%t(v1)+lambda_a[2]*v2%*%t(v2)+Psi_a))

  est_trt_cca <- c()
  est_ctst_cca <- c()
  est_ctst_pca <- c()
  eta_est <- c()

  for (repe in 1:repetition) {
    print(repe)
    dat_t <- mvrnorm(n = nt, mu = rep(0, p+q), Sigma = Sigma_t)
    dat_a <- mvrnorm(n = na, mu = rep(0, p+q), Sigma = Sigma_a)

    Xt <- dat_t[,1:p]
    Yt <- dat_t[,(p+1):(p+q)]
    Xa <- dat_a[,1:p]
    Ya <- dat_a[,(p+1):(p+q)]

    # for each dataset, simulate the response using true loadings and the generated data
    response_x <- Xt %*% u3 * lm_beta + rnorm(nt, sd = lm_sigma)

    Xt <- scale(Xt, center = TRUE, scale = FALSE)
    Yt <- scale(Yt, center = TRUE, scale = FALSE)
    Xa <- scale(Xa, center = TRUE, scale = FALSE)
    Ya <- scale(Ya, center = TRUE, scale = FALSE)

    # target cross covariance analysis
    CCA_trt <- PMD(cov(Xt, Yt), type="standard", K=3, sumabsu = sqrt(s), sumabsv = sqrt(s), center = FALSE, trace = FALSE)
    score_Xtrt <- Xt %*% CCA_trt$u[,1]
    est_trt_cca <- c(est_trt_cca, coefficients(lm(response_x~score_Xtrt))[2])

    # ancillary cross covariance analysis
    CCA_ctrl <- PMD(cov(Xa, Ya), type="standard", K=3, sumabsu = sqrt(s), sumabsv = sqrt(s), center = FALSE, trace = FALSE)

    # eta choice
    if(is.null(eta)){
      eta <- CCA_trt$d[1]/CCA_ctrl$d[1]
    }
    eta_est <- c(eta_est, eta)

    # s3CA
    contrast <- cov(Xt, Yt) - eta*cov(Xa, Ya)
    CCA_ctst <- PMD(contrast, type="standard", K=3, sumabsu = sqrt(s), sumabsv = sqrt(s), center = FALSE, trace = FALSE)
    score_Xctst <- Xt %*% CCA_ctst$u[,1]
    est_ctst_cca <- c(est_ctst_cca, coefficients(lm(response_x~score_Xctst))[2])

    # scPCA on X
    eta_cpca <- PMD(cov(Xt), sumabsv = sqrt(s), sumabsu = sqrt(s), K=2, type = "standard",
                    center = FALSE, trace = FALSE)$d[1] / PMD(cov(Xa), sumabsv = sqrt(s), sumabsu = sqrt(s), K=2, type = "standard",
                                                              center = FALSE, trace = FALSE)$d[1]
    PCA_ctst <- PMD(cov(Xt)-eta_cpca*cov(Xa), sumabsv = sqrt(s), sumabsu = sqrt(s), K=2, type = "standard", center = FALSE, trace = FALSE)
    score_XcPCA <- Xt%*%PCA_ctst$v[,1]
    est_ctst_pca <- c(est_ctst_pca, coefficients(lm(response_x~score_XcPCA))[2])
  }
  return(data.frame(est_trt_cca = est_trt_cca,
                    est_ctst_cca = est_ctst_cca,
                    est_ctst_pca = est_ctst_pca,
                    eta_est = eta_est))
}
